Update to timed v0.13
adfinis-sygroup/timed-chart pull request #19
Opened 2020-04-14 14:24 UTC by hairmare

2020-04-15 09:29 UTC, sbor23 commented
sensible default is included in the timed-backend settings

2020-04-15 15:01 UTC, strixBE reviewed
why `0.13` and not `0.13.0`?

2020-04-15 15:03 UTC, MrStrix commented
> sensible default is included in the timed-backend settings

Does this mean our test fails with a false-negative and we ignore it or do we need to take action?

2020-04-15 15:05 UTC, sbor23 commented
> > sensible default is included in the timed-backend settings
> 
> Does this mean our test fails with a false-negative and we ignore it or do we need to take action?

I means that we changed that yesterday and the CI probably has to be run again to pick up the changes.

2020-04-15 15:10 UTC, sbor23 commented
> why `0.13` and not `0.13.0`?

This is the actual tag. But we're tagging the 0.13.1 bugfix release in a matter of hours so this should be fixed soon. ;)

2020-04-15 16:34 UTC, strixBE requested changes

2020-04-15 16:34 UTC, MrStrix commented on charts/timed/Chart.yaml
> +appVersion: v0.13
please bump to v0.13.1 directly

2020-04-15 17:30 UTC, hairmare commented
> why 0.13 and not 0.13.0?

It should have been 0.13.0 and we're fixing this going forward.

I just updated the PR to use 0.13.1.

2020-04-16 12:16 UTC, MrStrix commented
waiting for merge of https://github.com/adfinis-sygroup/timed-frontend/pull/423 and pushing new image

2020-04-16 15:52 UTC, strixBE approved these changes
lgtm

2020-04-16 15:52 UTC, merged